### ISSUE TITLE
Unable to install simsense 

### ISSUE THREAD

**Issue by laukik29** [youwyu/Adaptive-Diffusion-Terrain#2]
Upon following the readme for installation, changing the cuda path, error with simsense installation.

**Comment by youwyu** [comment]
Hi, Thank You for Using Our Work. There are few things you need to consider:
1. Make sure the ~/.bashrc includes the following and XXX is your CUDA Toolkit version
```shell
export CUDA_HOME=/usr/local/cuda-XXX
export PATH=/usr/local/cuda-XXX/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-XXX/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
2. Change the CUDA path in contexts/simsense/setup.py line 35
```shell
'-DCMAKE_CUDA_COMPILER=/usr/local/cuda-XXX/bin/nvcc'
```
3. Make sure you have cmake at version higher than 3.18
by checking here
```shell
cmake --version
```
if not, please follow the readme to update the cmake.

Please also show me the errors if they still exist.

**Comment by laukik29** [comment]
Hi, Thank you so much for the response. 
I have included my CUDA path in the ~/.bashrc
Changed the path to CUDA in setup.py. I am using CUDA version 'cuda-12.0'
my cmake version is 3.31.0
errors still exist, please find error mentioned.



`Obtaining file:///...Adaptive-Diffusion-Terrain/contexts/simsense
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home.../Adaptive-Diffusion-Terrain/contexts/simsense/setup.py", line 6, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "/home/...miniconda3/envs/ADTG/lib/python3.8/site-packages/torch/__init__.py", line 290, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /home/.../miniconda3/envs/ADTG/lib/python3.8/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by youwyu** [comment]
The easiest way is to reinstall PyTorch for CUDA 11.8 since you are using CUDA 12.0.
```shell
pip uninstall torch torchvision
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```
If this cannot help, try to debug the link by
```shell
ldd ~/miniconda3/envs/ADTG/lib/python3.8/site-packages/nvidia/cusparse/lib/libcusparse.so.12
```

**Comment by laukik29** [comment]
Hi thank you for the help, I was able to install the package, may I know the source of 'DepthSensor' in simsense package, since it has trouble importing it. 
Thank you

**Comment by youwyu** [comment]
It's in contexts/simsense/python/package/__init__.py. If you can install the package, you should be able to use it freely, such as
```shell
python -c "import simsense"
```

**Comment by laukik29** [comment]
Hi, so the problem is in offroad_env.py, it is unable to import DepthSensor from simsense, where as simsense is properly installed. When checked in contexts/simsense/python/package/init.py, it is also unable to execute ".pysimsense import DepthSensorEngine" from the pysimsense.cpp. 
Is it so that the build file of simsense does not include this package?

**Comment by youwyu** [comment]
Hi, Please do
```shell
pip install contexts/simsense
```

**Comment by laukik29** [comment]
Hi thank you for the help, I am able to run the code now, until it gave a value error 
        if len(envs_success_rate) != len(active_indices):
            raise ValueError("The length of envs_success_rate must match the number of active environments.")
            
I have changed the number of agents as per my Vram but what should I set the envs_success_rste to ? default is set as None

**Comment by youwyu** [comment]
We updated the code to accommodate the issue. BTW, it's more suggestable to lower the number of terrains per column and row to N < 10 for the GPU Ram.

**Comment by laukik29** [comment]
Hi, thanks for the update, am able to run the auto_train.py to train the teacher. Do you also have a play script included for the policy visualization?

**Comment by youwyu** [comment]
I'm glad you can run this smoothly. Please see the updated code by
```shell
python3 -m rl_agents.play_teacher
```
Note: I did not test the code.
